name: Ruby

on: [push]

jobs:
  spec:
    runs-on: ubuntu-latest
    name: Run specs in ruby v${{ matrix.ruby }} rails v${{ matrix.rails }}
    strategy:
      matrix:
        # ruby: [ '2.6', '2.7', '3.0' ]
        # rails: [ '6.0', '6.1' ]
        ruby: [ '2.6' ]
        rails: [ '5.2', '6.0' ]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Install dependencies
      env:
        BUNDLE_GEMFILE: gemfiles/rails.${{ matrix.rails }}.gemfile
      run: bundle install

    - name: Run specs
      env:
        BUNDLE_GEMFILE: gemfiles/rails.${{ matrix.rails }}.gemfile
      run: bundle exec rake spec
